// generated by lalr1_gen.

// Copyright (c) Peter Williams <pwil3058@bigpond.net.au> <pwil3058@gmail.com>

use lalr1;
use lexan;

#[allow(dead_code)]
#[derive(Debug, Default, PartialEq, Eq)]
pub enum CommandAction {
    SetEnvVar(String, String),
    UnsetEnvVar(String),
    ChangeDir(String),
    RunProgram(
        String,
        Vec<String>,
        Option<String>,
        Option<(String, bool)>,
        Option<(String, bool)>,
    ),
    #[default]
    Default,
}

#[cfg(test)]
pub mod parser_tests;

impl lalr1::ReportError<AATerminal> for CommandAction {}

#[allow(dead_code)]
#[derive(Debug, Default, Clone)]
pub enum AttributeData {
    Token(lexan::Token<AATerminal>),
    Error(lalr1::Error<AATerminal>),
    String(String),
    Id(String),
    Args(Vec<String>),
    Input(Option<String>),
    Output(Option<(String, bool)>),
    #[default]
    Default,
}

impl AttributeData {
    fn args(&self) -> Vec<String> {
        match self {
            Self::Args(args) => args.clone(),
            _ => panic!("Invalid AttributeData variant"),
        }
    }

    fn args_mut(&mut self) -> &mut Vec<String> {
        match self {
            Self::Args(args) => args,
            _ => panic!("Invalid AttributeData variant"),
        }
    }

    fn input(&self) -> Option<String> {
        match self {
            Self::Input(input) => input.clone(),
            _ => panic!("Invalid AttributeData variant"),
        }
    }

    fn output(&self) -> Option<(String, bool)> {
        match self {
            Self::Output(output) => output.clone(),
            _ => panic!("Invalid AttributeData variant"),
        }
    }

    fn string(&self) -> String {
        match self {
            Self::String(string) => string.clone(),
            _ => panic!("Invalid AttributeData variant"),
        }
    }

    fn id(&self) -> String {
        match self {
            Self::Id(string) => string.clone(),
            _ => panic!("Invalid AttributeData variant"),
        }
    }
}

impl From<lexan::Token<AATerminal>> for AttributeData {
    fn from(input: lexan::Token<AATerminal>) -> Self {
        match input.tag() {
            AATerminal::STRING => AttributeData::String(input.lexeme().to_string()),
            AATerminal::ID => AttributeData::Id(input.lexeme().to_string()),
            _ => AttributeData::Token(input.clone()),
        }
    }
}

impl From<lalr1::Error<AATerminal>> for AttributeData {
    fn from(error: lalr1::Error<AATerminal>) -> Self {
        AttributeData::Error(error.clone())
    }
}

use std::collections::BTreeSet;

macro_rules! btree_set {
    () => { BTreeSet::new() };
    ( $( $x:expr ),* ) => {
        {
            let mut set = BTreeSet::new();
            $( set.insert($x); )*
            set
        }
    };
    ( $( $x:expr ),+ , ) => {
        btree_set![ $( $x ), * ]
    };
}

#[derive(Debug, Clone, Copy, PartialOrd, Ord, PartialEq, Eq)]
pub enum AATerminal {
    AAEnd,
    APPEND,
    ASSIGN,
    CDIR,
    EAPPEND,
    EOL,
    EOVERWRITE,
    ID,
    INPUT,
    OVERWRITE,
    STRING,
    UNSET,
}

impl std::fmt::Display for AATerminal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            AATerminal::AAEnd => write!(f, r###"AAEnd"###),
            AATerminal::APPEND => write!(f, r###"">>""###),
            AATerminal::ASSIGN => write!(f, r###""=""###),
            AATerminal::CDIR => write!(f, r###""cd""###),
            AATerminal::EAPPEND => write!(f, r###""2>>""###),
            AATerminal::EOL => write!(f, r###"EOL"###),
            AATerminal::EOVERWRITE => write!(f, r###""2>""###),
            AATerminal::ID => write!(f, r###"ID"###),
            AATerminal::INPUT => write!(f, r###""<""###),
            AATerminal::OVERWRITE => write!(f, r###"">""###),
            AATerminal::STRING => write!(f, r###"STRING"###),
            AATerminal::UNSET => write!(f, r###""unset""###),
        }
    }
}

lazy_static::lazy_static! {
    static ref AALEXAN: lexan::LexicalAnalyzer<AATerminal> = {
        use AATerminal::*;
        lexan::LexicalAnalyzer::new(
            &[
                (EOVERWRITE, r###"2>"###),
                (EAPPEND, r###"2>>"###),
                (INPUT, r###"<"###),
                (ASSIGN, r###"="###),
                (OVERWRITE, r###">"###),
                (APPEND, r###">>"###),
                (CDIR, r###"cd"###),
                (UNSET, r###"unset"###),
            ],
            &[
                (STRING, r###"("(\\"|[^"\t\r\n\v\f])+")"###),
                (ID, r###"([\w\d._\-/:]+)"###),
                (EOL, r###"(\n)"###),
            ],
            &[
                r###"([ \t]+)"###,
            ],
            AAEnd,
        )
    };
}

#[derive(Debug, Clone, Copy, PartialOrd, Ord, PartialEq, Eq)]
pub enum AANonTerminal {
    AAStart,
    Args,
    CommandAction,
    ErrOutput,
    Input,
    Output,
}

impl std::fmt::Display for AANonTerminal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            AANonTerminal::AAStart => write!(f, r"AAStart"),
            AANonTerminal::Args => write!(f, r"Args"),
            AANonTerminal::CommandAction => write!(f, r"CommandAction"),
            AANonTerminal::ErrOutput => write!(f, r"ErrOutput"),
            AANonTerminal::Input => write!(f, r"Input"),
            AANonTerminal::Output => write!(f, r"Output"),
        }
    }
}

impl lalr1::Parser<AATerminal, AANonTerminal, AttributeData> for CommandAction {
    fn lexical_analyzer(&self) -> &lexan::LexicalAnalyzer<AATerminal> {
        &AALEXAN
    }

    fn viable_error_recovery_states(_token: &AATerminal) -> BTreeSet<u32> {
        btree_set![]
    }

    fn look_ahead_set(state: u32) -> BTreeSet<AATerminal> {
        use AATerminal::*;
        return match state {
            0 => btree_set![CDIR, UNSET, ID],
            1 => btree_set![AAEnd],
            2 => {
                btree_set![APPEND, ASSIGN, EAPPEND, EOVERWRITE, INPUT, OVERWRITE, ID, STRING, AAEnd]
            }
            3 => btree_set![ID],
            4 => btree_set![ID],
            5 => btree_set![ID, STRING],
            6 => btree_set![APPEND, EAPPEND, EOVERWRITE, INPUT, OVERWRITE, ID, STRING, AAEnd],
            7 => btree_set![AAEnd],
            8 => btree_set![AAEnd],
            9 => btree_set![AAEnd],
            10 => btree_set![AAEnd],
            11 => btree_set![APPEND, EAPPEND, EOVERWRITE, OVERWRITE, AAEnd],
            12 => btree_set![APPEND, EAPPEND, EOVERWRITE, INPUT, OVERWRITE, ID, STRING, AAEnd],
            13 => btree_set![APPEND, EAPPEND, EOVERWRITE, INPUT, OVERWRITE, ID, STRING, AAEnd],
            14 => btree_set![ID],
            15 => btree_set![EAPPEND, EOVERWRITE, AAEnd],
            16 => btree_set![ID],
            17 => btree_set![ID],
            18 => btree_set![APPEND, EAPPEND, EOVERWRITE, OVERWRITE, AAEnd],
            19 => btree_set![AAEnd],
            20 => btree_set![ID],
            21 => btree_set![ID],
            22 => btree_set![EAPPEND, EOVERWRITE, AAEnd],
            23 => btree_set![EAPPEND, EOVERWRITE, AAEnd],
            24 => btree_set![AAEnd],
            25 => btree_set![AAEnd],
            _ => panic!("illegal state: {state}"),
        };
    }

    fn next_action(&self, aa_state: u32, aa_token: &lexan::Token<AATerminal>) -> lalr1::Action {
        use lalr1::Action;
        use AATerminal::*;
        let aa_tag = *aa_token.tag();
        return match aa_state {
            0 => match aa_tag {
                CDIR => Action::Shift(4),
                UNSET => Action::Shift(3),
                ID => Action::Shift(2),
                _ => Action::SyntaxError,
            },
            1 => match aa_tag {
                // AAStart: CommandAction #(NonAssoc, 0)
                AAEnd => Action::Accept,
                _ => Action::SyntaxError,
            },
            2 => match aa_tag {
                ASSIGN => Action::Shift(5),
                // Args: <empty> #(NonAssoc, 0)
                APPEND | EAPPEND | EOVERWRITE | INPUT | OVERWRITE | ID | STRING | AAEnd => {
                    Action::Reduce(6)
                }
                _ => Action::SyntaxError,
            },
            3 => match aa_tag {
                ID => Action::Shift(7),
                _ => Action::SyntaxError,
            },
            4 => match aa_tag {
                ID => Action::Shift(8),
                _ => Action::SyntaxError,
            },
            5 => match aa_tag {
                ID => Action::Shift(9),
                STRING => Action::Shift(10),
                _ => Action::SyntaxError,
            },
            6 => match aa_tag {
                INPUT => Action::Shift(14),
                ID => Action::Shift(12),
                STRING => Action::Shift(13),
                // Input: <empty> #(NonAssoc, 0)
                APPEND | EAPPEND | EOVERWRITE | OVERWRITE | AAEnd => Action::Reduce(9),
                _ => Action::SyntaxError,
            },
            7 => match aa_tag {
                // CommandAction: "unset" ID #(NonAssoc, 0)
                AAEnd => Action::Reduce(3),
                _ => Action::SyntaxError,
            },
            8 => match aa_tag {
                // CommandAction: "cd" ID #(NonAssoc, 0)
                AAEnd => Action::Reduce(4),
                _ => Action::SyntaxError,
            },
            9 => match aa_tag {
                // CommandAction: ID "=" ID #(NonAssoc, 0)
                AAEnd => Action::Reduce(1),
                _ => Action::SyntaxError,
            },
            10 => match aa_tag {
                // CommandAction: ID "=" STRING #(NonAssoc, 0)
                AAEnd => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            11 => match aa_tag {
                APPEND => Action::Shift(17),
                OVERWRITE => Action::Shift(16),
                // Output: <empty> #(NonAssoc, 0)
                EAPPEND | EOVERWRITE | AAEnd => Action::Reduce(11),
                _ => Action::SyntaxError,
            },
            12 => match aa_tag {
                // Args: Args ID #(NonAssoc, 0)
                APPEND | EAPPEND | EOVERWRITE | INPUT | OVERWRITE | ID | STRING | AAEnd => {
                    Action::Reduce(7)
                }
                _ => Action::SyntaxError,
            },
            13 => match aa_tag {
                // Args: Args STRING #(NonAssoc, 0)
                APPEND | EAPPEND | EOVERWRITE | INPUT | OVERWRITE | ID | STRING | AAEnd => {
                    Action::Reduce(8)
                }
                _ => Action::SyntaxError,
            },
            14 => match aa_tag {
                ID => Action::Shift(18),
                _ => Action::SyntaxError,
            },
            15 => match aa_tag {
                EAPPEND => Action::Shift(21),
                EOVERWRITE => Action::Shift(20),
                // ErrOutput: <empty> #(NonAssoc, 0)
                AAEnd => Action::Reduce(14),
                _ => Action::SyntaxError,
            },
            16 => match aa_tag {
                ID => Action::Shift(22),
                _ => Action::SyntaxError,
            },
            17 => match aa_tag {
                ID => Action::Shift(23),
                _ => Action::SyntaxError,
            },
            18 => match aa_tag {
                // Input: "<" ID #(NonAssoc, 0)
                APPEND | EAPPEND | EOVERWRITE | OVERWRITE | AAEnd => Action::Reduce(10),
                _ => Action::SyntaxError,
            },
            19 => match aa_tag {
                // CommandAction: ID Args Input Output ErrOutput #(NonAssoc, 0)
                AAEnd => Action::Reduce(5),
                _ => Action::SyntaxError,
            },
            20 => match aa_tag {
                ID => Action::Shift(24),
                _ => Action::SyntaxError,
            },
            21 => match aa_tag {
                ID => Action::Shift(25),
                _ => Action::SyntaxError,
            },
            22 => match aa_tag {
                // Output: ">" ID #(NonAssoc, 0)
                EAPPEND | EOVERWRITE | AAEnd => Action::Reduce(12),
                _ => Action::SyntaxError,
            },
            23 => match aa_tag {
                // Output: ">>" ID #(NonAssoc, 0)
                EAPPEND | EOVERWRITE | AAEnd => Action::Reduce(13),
                _ => Action::SyntaxError,
            },
            24 => match aa_tag {
                // ErrOutput: "2>" ID #(NonAssoc, 0)
                AAEnd => Action::Reduce(15),
                _ => Action::SyntaxError,
            },
            25 => match aa_tag {
                // ErrOutput: "2>>" ID #(NonAssoc, 0)
                AAEnd => Action::Reduce(16),
                _ => Action::SyntaxError,
            },
            _ => panic!("illegal state: {aa_state}"),
        };
    }

    fn production_data(production_id: u32) -> (AANonTerminal, usize) {
        match production_id {
            0 => (AANonTerminal::AAStart, 1),
            1 => (AANonTerminal::CommandAction, 3),
            2 => (AANonTerminal::CommandAction, 3),
            3 => (AANonTerminal::CommandAction, 2),
            4 => (AANonTerminal::CommandAction, 2),
            5 => (AANonTerminal::CommandAction, 5),
            6 => (AANonTerminal::Args, 0),
            7 => (AANonTerminal::Args, 2),
            8 => (AANonTerminal::Args, 2),
            9 => (AANonTerminal::Input, 0),
            10 => (AANonTerminal::Input, 2),
            11 => (AANonTerminal::Output, 0),
            12 => (AANonTerminal::Output, 2),
            13 => (AANonTerminal::Output, 2),
            14 => (AANonTerminal::ErrOutput, 0),
            15 => (AANonTerminal::ErrOutput, 2),
            16 => (AANonTerminal::ErrOutput, 2),
            _ => panic!("malformed production data table"),
        }
    }

    fn goto_state(lhs: &AANonTerminal, current_state: u32) -> u32 {
        return match current_state {
            0 => match lhs {
                AANonTerminal::CommandAction => 1,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            2 => match lhs {
                AANonTerminal::Args => 6,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            6 => match lhs {
                AANonTerminal::Input => 11,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            11 => match lhs {
                AANonTerminal::Output => 15,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            15 => match lhs {
                AANonTerminal::ErrOutput => 19,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
        };
    }

    fn do_semantic_action<F: FnMut(String, String)>(
        &mut self,
        aa_production_id: u32,
        aa_rhs: Vec<AttributeData>,
        mut aa_inject: F,
    ) -> AttributeData {
        let mut aa_lhs = if let Some(a) = aa_rhs.first() {
            a.clone()
        } else {
            AttributeData::default()
        };
        match aa_production_id {
            1 => {
                // CommandAction: ID "=" ID #(NonAssoc, 0)

                *self = CommandAction::SetEnvVar(aa_rhs[0].id(), aa_rhs[2].id());
            }
            2 => {
                // CommandAction: ID "=" STRING #(NonAssoc, 0)

                *self = CommandAction::SetEnvVar(aa_rhs[0].id(), aa_rhs[2].string());
            }
            3 => {
                // CommandAction: "unset" ID #(NonAssoc, 0)

                *self = CommandAction::UnsetEnvVar(aa_rhs[1].id());
            }
            4 => {
                // CommandAction: "cd" ID #(NonAssoc, 0)

                *self = CommandAction::ChangeDir(aa_rhs[1].id());
            }
            5 => {
                // CommandAction: ID Args Input Output ErrOutput #(NonAssoc, 0)

                *self = CommandAction::RunProgram(
                    aa_rhs[0].id(),
                    aa_rhs[1].args(),
                    aa_rhs[2].input(),
                    aa_rhs[3].output(),
                    aa_rhs[4].output(),
                );
            }
            6 => {
                // Args: <empty> #(NonAssoc, 0)

                aa_lhs = AttributeData::Args(vec![]);
            }
            7 => {
                // Args: Args ID #(NonAssoc, 0)

                aa_lhs.args_mut().push(aa_rhs[1].id())
            }
            8 => {
                // Args: Args STRING #(NonAssoc, 0)

                aa_lhs.args_mut().push(aa_rhs[1].string())
            }
            9 => {
                // Input: <empty> #(NonAssoc, 0)
                aa_lhs = AttributeData::Input(None);
            }
            10 => {
                // Input: "<" ID #(NonAssoc, 0)
                aa_lhs = AttributeData::Input(Some(aa_rhs[1].id()));
            }
            11 => {
                // Output: <empty> #(NonAssoc, 0)
                aa_lhs = AttributeData::Output(None);
            }
            12 => {
                // Output: ">" ID #(NonAssoc, 0)
                aa_lhs = AttributeData::Output(Some((aa_rhs[1].id(), true)));
            }
            13 => {
                // Output: ">>" ID #(NonAssoc, 0)
                aa_lhs = AttributeData::Output(Some((aa_rhs[1].id(), false)));
            }
            14 => {
                // ErrOutput: <empty> #(NonAssoc, 0)
                aa_lhs = AttributeData::Output(None);
            }
            15 => {
                // ErrOutput: "2>" ID #(NonAssoc, 0)
                aa_lhs = AttributeData::Output(Some((aa_rhs[1].id(), true)));
            }
            16 => {
                // ErrOutput: "2>>" ID #(NonAssoc, 0)
                aa_lhs = AttributeData::Output(Some((aa_rhs[1].id(), false)));
            }
            _ => aa_inject(String::new(), String::new()),
        };
        aa_lhs
    }
}
