// generated by lalr1_gen.

// Copyright 2026 (c) Peter Williams <pwil3058@bigpond.net.au> <pwil3058@gmail.com>
//
#[derive(Debug, Default, PartialEq, Eq)]
pub enum CommandAction {
    SetEnvVar(String, String),
    UnsetEnvVar(String),
    ChangeDir(String),
    RunProgram(
        String,
        Vec<String>,
        Option<String>,
        Option<(String, bool)>,
        Option<(String, bool)>,
    ),
    #[default]
    Default,
}

impl lalr1::ReportParseError<AATerminal> for CommandAction {}

#[derive(Debug, Default, Clone)]
pub enum AttributeData {
    String(String),
    Id(String),
    Args(Vec<String>),
    Input(Option<String>),
    Output(Option<(String, bool)>),
    Assign(String),
    #[default]
    Default,
}

impl AttributeData {
    fn args(&self) -> Vec<String> {
        match self {
            Self::Args(args) => args.clone(),
            _ => panic!("Invalid AttributeData variant"),
        }
    }

    fn args_mut(&mut self) -> &mut Vec<String> {
        match self {
            Self::Args(args) => args,
            _ => panic!("Invalid AttributeData variant"),
        }
    }

    fn input(&self) -> Option<String> {
        match self {
            Self::Input(input) => input.clone(),
            _ => panic!("Invalid AttributeData variant"),
        }
    }

    fn output(&self) -> Option<(String, bool)> {
        match self {
            Self::Output(output) => output.clone(),
            _ => panic!("Invalid AttributeData variant"),
        }
    }

    fn string(&self) -> String {
        match self {
            Self::String(string) => string.clone(),
            _ => panic!("Invalid AttributeData variant"),
        }
    }

    fn assign(&self) -> String {
        match self {
            Self::Assign(s) => s.clone(),
            _ => panic!("Invalid AttributeData variant: expected Assign"),
        }
    }

    fn id(&self) -> String {
        match self {
            Self::Id(string) => string.clone(),
            _ => panic!("Invalid AttributeData variant"),
        }
    }
}

impl From<lexan::Token<AATerminal>> for AttributeData {
    fn from(input: lexan::Token<AATerminal>) -> Self {
        match input.tag() {
            AATerminal::String => {
                let lexeme = input.lexeme();
                let clean_string =
                    if lexeme.starts_with('"') && lexeme.ends_with('"') && lexeme.len() >= 2 {
                        lexeme[1..lexeme.len() - 1].to_string()
                    } else {
                        lexeme.to_string()
                    };
                AttributeData::String(clean_string)
            }
            AATerminal::Assign => AttributeData::Assign(input.lexeme().to_string()),
            AATerminal::Id => AttributeData::Id(input.lexeme().to_string()),
            _ => AttributeData::Default,
        }
    }
}

impl From<lalr1::SyntaxError<AATerminal>> for AttributeData {
    fn from(_error: lalr1::SyntaxError<AATerminal>) -> Self {
        AttributeData::Default
    }
}

use std::sync::LazyLock;

use lexan::{lexicon, LexicalAnalyzer, TokenStream};

use lalr1::{Error, OrderedSet};

macro_rules! ordered_set {
    () => { OrderedSet::new() };
    ( $( $x:expr ),* ) => {
        {
            let mut set = OrderedSet::new();
            $( set.insert($x); )*
            set
        }
    };
    ( $( $x:expr ),+ , ) => {
        ordered_set![ $( $x ), * ]
    };
}

#[derive(Debug, Default, Clone, Copy, PartialOrd, Ord, PartialEq, Eq)]
pub enum AATerminal {
    #[default]
    AAEnd,
    Append,
    Assign,
    ChangeDir,
    EAppend,
    EOverWrite,
    Eol,
    Id,
    InputFile,
    OverWrite,
    String,
    Unset,
}

impl std::fmt::Display for AATerminal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            AATerminal::AAEnd => write!(f, r###"AAEnd"###),
            AATerminal::Append => write!(f, r###"">>""###),
            AATerminal::Assign => write!(f, r###"Assign"###),
            AATerminal::ChangeDir => write!(f, r###""cd""###),
            AATerminal::EAppend => write!(f, r###""2>>""###),
            AATerminal::EOverWrite => write!(f, r###""2>""###),
            AATerminal::Eol => write!(f, r###"Eol"###),
            AATerminal::Id => write!(f, r###"Id"###),
            AATerminal::InputFile => write!(f, r###""<""###),
            AATerminal::OverWrite => write!(f, r###"">""###),
            AATerminal::String => write!(f, r###"String"###),
            AATerminal::Unset => write!(f, r###""unset""###),
        }
    }
}

static AALEXAN: LazyLock<Result<LexicalAnalyzer<AATerminal>, lexicon::Error<AATerminal>>> =
    LazyLock::new(|| {
        use AATerminal::*;
        lexan::LexicalAnalyzer::new(
            &[
                (EOverWrite, r###"2>"###),
                (EAppend, r###"2>>"###),
                (InputFile, r###"<"###),
                (OverWrite, r###">"###),
                (Append, r###">>"###),
                (ChangeDir, r###"cd"###),
                (Unset, r###"unset"###),
            ],
            &[
                (String, r###"("(\\"|[^"])+")"###),
                (Id, r###"([\w\d._\-/:]+)"###),
                (
                    Assign,
                    r###"([\w\d._\-/:]+=(([\w\d._\-/:]+)|("(\\"|[^"])+")))"###,
                ),
                (Eol, r###"(\n)"###),
            ],
            &[r###"([ \t]+)"###],
            AAEnd,
        )
    });

#[derive(Debug, Clone, Copy, PartialOrd, Ord, PartialEq, Eq)]
pub enum AANonTerminal {
    AAStart,
    Args,
    CommandAction,
    ErrOutput,
    Input,
    Output,
}

impl std::fmt::Display for AANonTerminal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            AANonTerminal::AAStart => write!(f, r"AAStart"),
            AANonTerminal::Args => write!(f, r"Args"),
            AANonTerminal::CommandAction => write!(f, r"CommandAction"),
            AANonTerminal::ErrOutput => write!(f, r"ErrOutput"),
            AANonTerminal::Input => write!(f, r"Input"),
            AANonTerminal::Output => write!(f, r"Output"),
        }
    }
}

impl lalr1::Parser<AATerminal, AANonTerminal, AttributeData> for CommandAction {
    fn token_stream(
        &self,
        text: &str,
        label: &str,
    ) -> Result<TokenStream<AATerminal>, Error<AATerminal>> {
        let lexical_analyzer = AALEXAN.as_ref().map_err(|e| e.clone())?;
        Ok(lexical_analyzer.token_stream(text, label))
    }

    fn viable_error_recovery_states(_token: &AATerminal) -> OrderedSet<u32> {
        ordered_set![]
    }

    fn look_ahead_set(state: u32) -> OrderedSet<AATerminal> {
        use AATerminal::*;
        match state {
            0 => ordered_set![ChangeDir, Unset, Assign, Id],
            1 => ordered_set![AAEnd],
            2 => ordered_set![Eol],
            3 => ordered_set![Id],
            4 => ordered_set![Id],
            5 => ordered_set![
                Append, EAppend, EOverWrite, InputFile, OverWrite, Assign, Eol, Id, String
            ],
            6 => ordered_set![AAEnd],
            7 => ordered_set![Eol],
            8 => ordered_set![Eol],
            9 => ordered_set![
                Append, EAppend, EOverWrite, InputFile, OverWrite, Assign, Eol, Id, String
            ],
            10 => ordered_set![AAEnd],
            11 => ordered_set![AAEnd],
            12 => ordered_set![Append, EAppend, EOverWrite, OverWrite, Eol],
            13 => ordered_set![
                Append, EAppend, EOverWrite, InputFile, OverWrite, Assign, Eol, Id, String
            ],
            14 => ordered_set![
                Append, EAppend, EOverWrite, InputFile, OverWrite, Assign, Eol, Id, String
            ],
            15 => ordered_set![
                Append, EAppend, EOverWrite, InputFile, OverWrite, Assign, Eol, Id, String
            ],
            16 => ordered_set![Id],
            17 => ordered_set![EAppend, EOverWrite, Eol],
            18 => ordered_set![Id],
            19 => ordered_set![Id],
            20 => ordered_set![Append, EAppend, EOverWrite, OverWrite, Eol],
            21 => ordered_set![Eol],
            22 => ordered_set![Id],
            23 => ordered_set![Id],
            24 => ordered_set![EAppend, EOverWrite, Eol],
            25 => ordered_set![EAppend, EOverWrite, Eol],
            26 => ordered_set![AAEnd],
            27 => ordered_set![Eol],
            28 => ordered_set![Eol],
            _ => panic!("illegal state: {state}"),
        }
    }

    fn next_action(
        &self,
        aa_parse_stack: &lalr1::ParseStack<AATerminal, AANonTerminal, AttributeData>,
        aa_token: &lexan::Token<AATerminal>,
    ) -> lalr1::Action {
        use lalr1::Action;
        use AATerminal::*;
        let aa_tag = *aa_token.tag();
        let aa_state = aa_parse_stack.current_state();
        match aa_state {
            0 => match aa_tag {
                ChangeDir => Action::Shift(4),
                Unset => Action::Shift(3),
                Assign => Action::Shift(2),
                Id => Action::Shift(5),
                _ => Action::SyntaxError,
            },
            1 => match aa_tag {
                // AAStart: CommandAction #(NonAssoc, 0)
                AAEnd => Action::Accept,
                _ => Action::SyntaxError,
            },
            2 => match aa_tag {
                Eol => Action::Shift(6),
                _ => Action::SyntaxError,
            },
            3 => match aa_tag {
                Id => Action::Shift(7),
                _ => Action::SyntaxError,
            },
            4 => match aa_tag {
                Id => Action::Shift(8),
                _ => Action::SyntaxError,
            },
            5 => match aa_tag {
                // Args: <empty> #(NonAssoc, 0)
                Append | EAppend | EOverWrite | InputFile | OverWrite | Assign | Eol | Id
                | String => Action::Reduce(5),
                _ => Action::SyntaxError,
            },
            6 => match aa_tag {
                // CommandAction: Assign Eol #(NonAssoc, 0)
                AAEnd => Action::Reduce(1),
                _ => Action::SyntaxError,
            },
            7 => match aa_tag {
                Eol => Action::Shift(10),
                _ => Action::SyntaxError,
            },
            8 => match aa_tag {
                Eol => Action::Shift(11),
                _ => Action::SyntaxError,
            },
            9 => match aa_tag {
                InputFile => Action::Shift(16),
                Assign => Action::Shift(15),
                Id => Action::Shift(13),
                String => Action::Shift(14),
                // Input: <empty> #(NonAssoc, 0)
                Append | EAppend | EOverWrite | OverWrite | Eol => Action::Reduce(9),
                _ => Action::SyntaxError,
            },
            10 => match aa_tag {
                // CommandAction: "unset" Id Eol #(NonAssoc, 0)
                AAEnd => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            11 => match aa_tag {
                // CommandAction: "cd" Id Eol #(NonAssoc, 0)
                AAEnd => Action::Reduce(3),
                _ => Action::SyntaxError,
            },
            12 => match aa_tag {
                Append => Action::Shift(19),
                OverWrite => Action::Shift(18),
                // Output: <empty> #(NonAssoc, 0)
                EAppend | EOverWrite | Eol => Action::Reduce(11),
                _ => Action::SyntaxError,
            },
            13 => match aa_tag {
                // Args: Args Id #(NonAssoc, 0)
                Append | EAppend | EOverWrite | InputFile | OverWrite | Assign | Eol | Id
                | String => Action::Reduce(6),
                _ => Action::SyntaxError,
            },
            14 => match aa_tag {
                // Args: Args String #(NonAssoc, 0)
                Append | EAppend | EOverWrite | InputFile | OverWrite | Assign | Eol | Id
                | String => Action::Reduce(7),
                _ => Action::SyntaxError,
            },
            15 => match aa_tag {
                // Args: Args Assign #(NonAssoc, 0)
                Append | EAppend | EOverWrite | InputFile | OverWrite | Assign | Eol | Id
                | String => Action::Reduce(8),
                _ => Action::SyntaxError,
            },
            16 => match aa_tag {
                Id => Action::Shift(20),
                _ => Action::SyntaxError,
            },
            17 => match aa_tag {
                EAppend => Action::Shift(23),
                EOverWrite => Action::Shift(22),
                // ErrOutput: <empty> #(NonAssoc, 0)
                Eol => Action::Reduce(14),
                _ => Action::SyntaxError,
            },
            18 => match aa_tag {
                Id => Action::Shift(24),
                _ => Action::SyntaxError,
            },
            19 => match aa_tag {
                Id => Action::Shift(25),
                _ => Action::SyntaxError,
            },
            20 => match aa_tag {
                // Input: "<" Id #(NonAssoc, 0)
                Append | EAppend | EOverWrite | OverWrite | Eol => Action::Reduce(10),
                _ => Action::SyntaxError,
            },
            21 => match aa_tag {
                Eol => Action::Shift(26),
                _ => Action::SyntaxError,
            },
            22 => match aa_tag {
                Id => Action::Shift(27),
                _ => Action::SyntaxError,
            },
            23 => match aa_tag {
                Id => Action::Shift(28),
                _ => Action::SyntaxError,
            },
            24 => match aa_tag {
                // Output: ">" Id #(NonAssoc, 0)
                EAppend | EOverWrite | Eol => Action::Reduce(12),
                _ => Action::SyntaxError,
            },
            25 => match aa_tag {
                // Output: ">>" Id #(NonAssoc, 0)
                EAppend | EOverWrite | Eol => Action::Reduce(13),
                _ => Action::SyntaxError,
            },
            26 => match aa_tag {
                // CommandAction: Id Args Input Output ErrOutput Eol #(NonAssoc, 0)
                AAEnd => Action::Reduce(4),
                _ => Action::SyntaxError,
            },
            27 => match aa_tag {
                // ErrOutput: "2>" Id #(NonAssoc, 0)
                Eol => Action::Reduce(15),
                _ => Action::SyntaxError,
            },
            28 => match aa_tag {
                // ErrOutput: "2>>" Id #(NonAssoc, 0)
                Eol => Action::Reduce(16),
                _ => Action::SyntaxError,
            },
            _ => panic!("illegal state: {aa_state}"),
        }
    }

    fn production_data(production_id: u32) -> (AANonTerminal, usize) {
        match production_id {
            0 => (AANonTerminal::AAStart, 1),
            1 => (AANonTerminal::CommandAction, 2),
            2 => (AANonTerminal::CommandAction, 3),
            3 => (AANonTerminal::CommandAction, 3),
            4 => (AANonTerminal::CommandAction, 6),
            5 => (AANonTerminal::Args, 0),
            6 => (AANonTerminal::Args, 2),
            7 => (AANonTerminal::Args, 2),
            8 => (AANonTerminal::Args, 2),
            9 => (AANonTerminal::Input, 0),
            10 => (AANonTerminal::Input, 2),
            11 => (AANonTerminal::Output, 0),
            12 => (AANonTerminal::Output, 2),
            13 => (AANonTerminal::Output, 2),
            14 => (AANonTerminal::ErrOutput, 0),
            15 => (AANonTerminal::ErrOutput, 2),
            16 => (AANonTerminal::ErrOutput, 2),
            _ => panic!("malformed production data table"),
        }
    }

    fn goto_state(lhs: &AANonTerminal, current_state: u32) -> u32 {
        match current_state {
            0 => match lhs {
                AANonTerminal::CommandAction => 1,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            5 => match lhs {
                AANonTerminal::Args => 9,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            9 => match lhs {
                AANonTerminal::Input => 12,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            12 => match lhs {
                AANonTerminal::Output => 17,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            17 => match lhs {
                AANonTerminal::ErrOutput => 21,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
        }
    }

    fn do_semantic_action<F: FnMut(String, String)>(
        &mut self,
        aa_production_id: u32,
        aa_rhs: Vec<AttributeData>,
        mut aa_inject: F,
    ) -> AttributeData {
        let mut aa_lhs = if let Some(a) = aa_rhs.first() {
            a.clone()
        } else {
            AttributeData::default()
        };
        match aa_production_id {
            1 => {
                // CommandAction: Assign Eol #(NonAssoc, 0)

                let string = aa_rhs[0].assign();
                let mut parts = string.split('=');
                let id = parts.next().unwrap().to_string();
                let value = parts.next().unwrap();
                let value = if value.starts_with('"') && value.ends_with('"') && value.len() >= 2 {
                    value[1..value.len() - 1].to_string()
                } else {
                    value.to_string()
                };
                *self = CommandAction::SetEnvVar(id, value);
            }
            2 => {
                // CommandAction: "unset" Id Eol #(NonAssoc, 0)

                *self = CommandAction::UnsetEnvVar(aa_rhs[1].id());
            }
            3 => {
                // CommandAction: "cd" Id Eol #(NonAssoc, 0)

                *self = CommandAction::ChangeDir(aa_rhs[1].id());
            }
            4 => {
                // CommandAction: Id Args Input Output ErrOutput Eol #(NonAssoc, 0)

                *self = CommandAction::RunProgram(
                    aa_rhs[0].id(),
                    aa_rhs[1].args(),
                    aa_rhs[2].input(),
                    aa_rhs[3].output(),
                    aa_rhs[4].output(),
                );
            }
            5 => {
                // Args: <empty> #(NonAssoc, 0)

                aa_lhs = AttributeData::Args(vec![]);
            }
            6 => {
                // Args: Args Id #(NonAssoc, 0)

                aa_lhs.args_mut().push(aa_rhs[1].id())
            }
            7 => {
                // Args: Args String #(NonAssoc, 0)

                aa_lhs.args_mut().push(aa_rhs[1].string())
            }
            8 => {
                // Args: Args Assign #(NonAssoc, 0)

                aa_lhs.args_mut().push(aa_rhs[1].assign())
            }
            9 => {
                // Input: <empty> #(NonAssoc, 0)
                aa_lhs = AttributeData::Input(None);
            }
            10 => {
                // Input: "<" Id #(NonAssoc, 0)
                aa_lhs = AttributeData::Input(Some(aa_rhs[1].id()));
            }
            11 => {
                // Output: <empty> #(NonAssoc, 0)
                aa_lhs = AttributeData::Output(None);
            }
            12 => {
                // Output: ">" Id #(NonAssoc, 0)
                aa_lhs = AttributeData::Output(Some((aa_rhs[1].id(), true)));
            }
            13 => {
                // Output: ">>" Id #(NonAssoc, 0)
                aa_lhs = AttributeData::Output(Some((aa_rhs[1].id(), false)));
            }
            14 => {
                // ErrOutput: <empty> #(NonAssoc, 0)
                aa_lhs = AttributeData::Output(None);
            }
            15 => {
                // ErrOutput: "2>" Id #(NonAssoc, 0)
                aa_lhs = AttributeData::Output(Some((aa_rhs[1].id(), true)));
            }
            16 => {
                // ErrOutput: "2>>" Id #(NonAssoc, 0)
                aa_lhs = AttributeData::Output(Some((aa_rhs[1].id(), false)));
            }
            _ => aa_inject(String::new(), String::new()),
        };
        aa_lhs
    }
}
