// generated by lap_gen.

use lalr1;
use lexan;

#[allow(dead_code)]
#[derive(Debug, Default, PartialEq, Eq)]
pub enum CommandAction {
    SetEnvVar(String, String),
    UnsetEnvVar(String),
    RunProgram(
        String,
        Vec<String>,
        Option<String>,
        Option<String>,
        Option<String>,
    ),
    #[default]
    Default,
}

#[derive(Debug, Default)]
pub struct Command {
    pub string: String,
    pub action: CommandAction,
}

#[cfg(test)]
pub mod parser_tests;

impl lalr1::ReportError<AATerminal> for Command {}

#[allow(dead_code)]
#[derive(Debug, Default, Clone)]
pub enum AttributeData {
    Token(lexan::Token<AATerminal>),
    Error(lalr1::Error<AATerminal>),
    String(String),
    Id(String),
    #[default]
    Default,
}

impl AttributeData {
    fn string(&self) -> String {
        match self {
            Self::String(string) => string.clone(),
            _ => panic!("Invalid AttributeData variant"),
        }
    }

    fn id(&self) -> String {
        match self {
            Self::Id(string) => string.clone(),
            _ => panic!("Invalid AttributeData variant"),
        }
    }
}

impl From<lexan::Token<AATerminal>> for AttributeData {
    fn from(input: lexan::Token<AATerminal>) -> Self {
        match input.tag() {
            AATerminal::STRING => AttributeData::String(input.lexeme().to_string()),
            AATerminal::ID => AttributeData::Id(input.lexeme().to_string()),
            _ => AttributeData::Token(input.clone()),
        }
    }
}

impl From<lalr1::Error<AATerminal>> for AttributeData {
    fn from(error: lalr1::Error<AATerminal>) -> Self {
        AttributeData::Error(error.clone())
    }
}

use std::collections::BTreeSet;

macro_rules! btree_set {
    () => { BTreeSet::new() };
    ( $( $x:expr ),* ) => {
        {
            let mut set = BTreeSet::new();
            $( set.insert($x); )*
            set
        }
    };
    ( $( $x:expr ),+ , ) => {
        btree_set![ $( $x ), * ]
    };
}

#[derive(Debug, Clone, Copy, PartialOrd, Ord, PartialEq, Eq)]
pub enum AATerminal {
    AAEnd,
    ASSIGN,
    EOL,
    ID,
    STRING,
    UNSET,
}

impl std::fmt::Display for AATerminal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            AATerminal::AAEnd => write!(f, r###"AAEnd"###),
            AATerminal::ASSIGN => write!(f, r###""=""###),
            AATerminal::EOL => write!(f, r###"EOL"###),
            AATerminal::ID => write!(f, r###"ID"###),
            AATerminal::STRING => write!(f, r###"STRING"###),
            AATerminal::UNSET => write!(f, r###""unset""###),
        }
    }
}

lazy_static::lazy_static! {
    static ref AALEXAN: lexan::LexicalAnalyzer<AATerminal> = {
        use AATerminal::*;
        lexan::LexicalAnalyzer::new(
            &[
                (ASSIGN, r###"="###),
                (UNSET, r###"unset"###),
            ],
            &[
                (STRING, r###"("(\\"|[^"\t\r\n\v\f])+")"###),
                (ID, r###"([\w\d._\-/:]+)"###),
                (EOL, r###"(\n)"###),
            ],
            &[
                r###"([ \t]+)"###,
            ],
            AAEnd,
        )
    };
}

#[derive(Debug, Clone, Copy, PartialOrd, Ord, PartialEq, Eq)]
pub enum AANonTerminal {
    AAStart,
    Arg,
    Args,
    Command,
}

impl std::fmt::Display for AANonTerminal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            AANonTerminal::AAStart => write!(f, r"AAStart"),
            AANonTerminal::Arg => write!(f, r"Arg"),
            AANonTerminal::Args => write!(f, r"Args"),
            AANonTerminal::Command => write!(f, r"Command"),
        }
    }
}

impl lalr1::Parser<AATerminal, AANonTerminal, AttributeData> for Command {
    fn lexical_analyzer(&self) -> &lexan::LexicalAnalyzer<AATerminal> {
        &AALEXAN
    }

    fn viable_error_recovery_states(_token: &AATerminal) -> BTreeSet<u32> {
        btree_set![]
    }

    fn look_ahead_set(state: u32) -> BTreeSet<AATerminal> {
        use AATerminal::*;
        return match state {
            0 => btree_set![UNSET, ID],
            1 => btree_set![AAEnd],
            2 => btree_set![ASSIGN, ID, STRING, AAEnd],
            3 => btree_set![ID],
            4 => btree_set![ID, STRING],
            5 => btree_set![ID, STRING, AAEnd],
            6 => btree_set![AAEnd],
            7 => btree_set![AAEnd],
            8 => btree_set![AAEnd],
            9 => btree_set![ID, STRING, AAEnd],
            10 => btree_set![ID, STRING, AAEnd],
            11 => btree_set![ID, STRING, AAEnd],
            _ => panic!("illegal state: {state}"),
        };
    }

    fn next_action(&self, aa_state: u32, aa_token: &lexan::Token<AATerminal>) -> lalr1::Action {
        use lalr1::Action;
        use AATerminal::*;
        let aa_tag = *aa_token.tag();
        return match aa_state {
            0 => match aa_tag {
                UNSET => Action::Shift(3),
                ID => Action::Shift(2),
                _ => Action::SyntaxError,
            },
            1 => match aa_tag {
                // AAStart: Command #(NonAssoc, 0)
                AAEnd => Action::Accept,
                _ => Action::SyntaxError,
            },
            2 => match aa_tag {
                ASSIGN => Action::Shift(4),
                // Command: ID #(NonAssoc, 0)
                AAEnd => Action::Reduce(4),
                // Args: <empty> #(NonAssoc, 0)
                ID | STRING => Action::Reduce(6),
                _ => Action::SyntaxError,
            },
            3 => match aa_tag {
                ID => Action::Shift(6),
                _ => Action::SyntaxError,
            },
            4 => match aa_tag {
                ID => Action::Shift(7),
                STRING => Action::Shift(8),
                _ => Action::SyntaxError,
            },
            5 => match aa_tag {
                ID => Action::Shift(10),
                STRING => Action::Shift(11),
                // Command: ID Args #(NonAssoc, 0)
                AAEnd => Action::Reduce(5),
                _ => Action::SyntaxError,
            },
            6 => match aa_tag {
                // Command: "unset" ID #(NonAssoc, 0)
                AAEnd => Action::Reduce(3),
                _ => Action::SyntaxError,
            },
            7 => match aa_tag {
                // Command: ID "=" ID #(NonAssoc, 0)
                AAEnd => Action::Reduce(1),
                _ => Action::SyntaxError,
            },
            8 => match aa_tag {
                // Command: ID "=" STRING #(NonAssoc, 0)
                AAEnd => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            9 => match aa_tag {
                // Args: Args Arg #(NonAssoc, 0)
                ID | STRING | AAEnd => Action::Reduce(7),
                _ => Action::SyntaxError,
            },
            10 => match aa_tag {
                // Arg: ID #(NonAssoc, 0)
                ID | STRING | AAEnd => Action::Reduce(8),
                _ => Action::SyntaxError,
            },
            11 => match aa_tag {
                // Arg: STRING #(NonAssoc, 0)
                ID | STRING | AAEnd => Action::Reduce(9),
                _ => Action::SyntaxError,
            },
            _ => panic!("illegal state: {aa_state}"),
        };
    }

    fn production_data(production_id: u32) -> (AANonTerminal, usize) {
        match production_id {
            0 => (AANonTerminal::AAStart, 1),
            1 => (AANonTerminal::Command, 3),
            2 => (AANonTerminal::Command, 3),
            3 => (AANonTerminal::Command, 2),
            4 => (AANonTerminal::Command, 1),
            5 => (AANonTerminal::Command, 2),
            6 => (AANonTerminal::Args, 0),
            7 => (AANonTerminal::Args, 2),
            8 => (AANonTerminal::Arg, 1),
            9 => (AANonTerminal::Arg, 1),
            _ => panic!("malformed production data table"),
        }
    }

    fn goto_state(lhs: &AANonTerminal, current_state: u32) -> u32 {
        return match current_state {
            0 => match lhs {
                AANonTerminal::Command => 1,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            2 => match lhs {
                AANonTerminal::Args => 5,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            5 => match lhs {
                AANonTerminal::Arg => 9,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
        };
    }

    fn do_semantic_action<F: FnMut(String, String)>(
        &mut self,
        aa_production_id: u32,
        aa_rhs: Vec<AttributeData>,
        mut aa_inject: F,
    ) -> AttributeData {
        let mut aa_lhs = if let Some(a) = aa_rhs.first() {
            a.clone()
        } else {
            AttributeData::default()
        };
        match aa_production_id {
            1 => {
                // Command: ID "=" ID #(NonAssoc, 0)

                self.action = CommandAction::SetEnvVar(aa_rhs[0].id(), aa_rhs[2].id());
            }
            2 => {
                // Command: ID "=" STRING #(NonAssoc, 0)

                self.action = CommandAction::SetEnvVar(aa_rhs[0].id(), aa_rhs[2].string());
            }
            3 => {
                // Command: "unset" ID #(NonAssoc, 0)

                self.action = CommandAction::UnsetEnvVar(aa_rhs[1].id());
            }
            4 => {
                // Command: ID #(NonAssoc, 0)

                self.action = CommandAction::RunProgram(aa_rhs[0].id(), vec![], None, None, None);
            }
            5 => {
                // Command: ID Args #(NonAssoc, 0)
            }
            6 => {
                // Args: <empty> #(NonAssoc, 0)
            }
            _ => aa_inject(String::new(), String::new()),
        };
        aa_lhs
    }
}
