// generated by lap_gen.

use lalr1;
use lexan;

#[allow(dead_code)]
#[derive(Debug, Default)]
pub enum Command {
    SetEnvVar(String, String),
    #[default]
    Default,
}

#[cfg(test)]
pub mod parser_tests;

impl lalr1::ReportError<AATerminal> for Command {}

#[allow(dead_code)]
#[derive(Debug, Default, Clone)]
pub enum AttributeData {
    Token(lexan::Token<AATerminal>),
    Error(lalr1::Error<AATerminal>),
    String(String),
    Id(String),
    SetEnvVar(String, String),
    #[default]
    Default,
}

impl AttributeData {
    fn string(&self) -> &String {
        match self {
            Self::String(string) => string,
            _ => panic!("Invalid AttributeData variant"),
        }
    }

    fn id(&self) -> &String {
        match self {
            Self::Id(string) => string,
            _ => panic!("Invalid AttributeData variant"),
        }
    }

    fn set_env_var(&self) -> (&String, &String) {
        match self {
            Self::SetEnvVar(var, value) => (var, value),
            _ => panic!("Invalid AttributeData variant"),
        }
    }
}

impl From<lexan::Token<AATerminal>> for AttributeData {
    fn from(input: lexan::Token<AATerminal>) -> Self {
        match input.tag() {
            AATerminal::STRING => AttributeData::String(input.lexeme().to_string()),
            AATerminal::ID => AttributeData::Id(input.lexeme().to_string()),
            _ => AttributeData::Token(input.clone()),
        }
    }
}

impl From<lalr1::Error<AATerminal>> for AttributeData {
    fn from(error: lalr1::Error<AATerminal>) -> Self {
        AttributeData::Error(error.clone())
    }
}

use std::collections::BTreeSet;

macro_rules! btree_set {
    () => { BTreeSet::new() };
    ( $( $x:expr ),* ) => {
        {
            let mut set = BTreeSet::new();
            $( set.insert($x); )*
            set
        }
    };
    ( $( $x:expr ),+ , ) => {
        btree_set![ $( $x ), * ]
    };
}

#[derive(Debug, Clone, Copy, PartialOrd, Ord, PartialEq, Eq)]
pub enum AATerminal {
    AAEnd,
    ASSIGN,
    EOL,
    ID,
    STRING,
    UNSET,
    WS,
}

impl std::fmt::Display for AATerminal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            AATerminal::AAEnd => write!(f, r###"AAEnd"###),
            AATerminal::ASSIGN => write!(f, r###""=""###),
            AATerminal::EOL => write!(f, r###"EOL"###),
            AATerminal::ID => write!(f, r###"ID"###),
            AATerminal::STRING => write!(f, r###"STRING"###),
            AATerminal::UNSET => write!(f, r###""unset""###),
            AATerminal::WS => write!(f, r###"WS"###),
        }
    }
}

lazy_static::lazy_static! {
    static ref AALEXAN: lexan::LexicalAnalyzer<AATerminal> = {
        use AATerminal::*;
        lexan::LexicalAnalyzer::new(
            &[
                (ASSIGN, r###"="###),
                (UNSET, r###"unset"###),
            ],
            &[
                (STRING, r###"("(\\"|[^"\t\r\n\v\f])+")"###),
                (WS, r###"([ \t]+)"###),
                (ID, r###"([\w\d._\-/:]+)"###),
                (EOL, r###"(\n)"###),
            ],
            &[
            ],
            AAEnd,
        )
    };
}

#[derive(Debug, Clone, Copy, PartialOrd, Ord, PartialEq, Eq)]
pub enum AANonTerminal {
    AAStart,
    Command,
    SetEnvVar,
    UnsetEnvVar,
}

impl std::fmt::Display for AANonTerminal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            AANonTerminal::AAStart => write!(f, r"AAStart"),
            AANonTerminal::Command => write!(f, r"Command"),
            AANonTerminal::SetEnvVar => write!(f, r"SetEnvVar"),
            AANonTerminal::UnsetEnvVar => write!(f, r"UnsetEnvVar"),
        }
    }
}

impl lalr1::Parser<AATerminal, AANonTerminal, AttributeData> for Command {
    fn lexical_analyzer(&self) -> &lexan::LexicalAnalyzer<AATerminal> {
        &AALEXAN
    }

    fn viable_error_recovery_states(_token: &AATerminal) -> BTreeSet<u32> {
        btree_set![]
    }

    fn look_ahead_set(state: u32) -> BTreeSet<AATerminal> {
        use AATerminal::*;
        return match state {
            0 => btree_set![UNSET, ID, STRING],
            1 => btree_set![AAEnd],
            2 => btree_set![WS],
            3 => btree_set![AAEnd],
            4 => btree_set![AAEnd],
            5 => btree_set![ASSIGN],
            6 => btree_set![WS],
            7 => btree_set![ID],
            8 => btree_set![ID, STRING],
            9 => btree_set![ID],
            10 => btree_set![AAEnd],
            11 => btree_set![AAEnd],
            12 => btree_set![AAEnd],
            13 => btree_set![AAEnd],
            _ => panic!("illegal state: {state}"),
        };
    }

    fn next_action(&self, aa_state: u32, aa_token: &lexan::Token<AATerminal>) -> lalr1::Action {
        use lalr1::Action;
        use AATerminal::*;
        let aa_tag = *aa_token.tag();
        return match aa_state {
            0 => match aa_tag {
                UNSET => Action::Shift(6),
                ID => Action::Shift(5),
                STRING => Action::Shift(2),
                _ => Action::SyntaxError,
            },
            1 => match aa_tag {
                // AAStart: Command #(NonAssoc, 0)
                AAEnd => Action::Accept,
                _ => Action::SyntaxError,
            },
            2 => match aa_tag {
                WS => Action::Shift(7),
                _ => Action::SyntaxError,
            },
            3 => match aa_tag {
                // Command: SetEnvVar #(NonAssoc, 0)
                AAEnd => Action::Reduce(2),
                _ => Action::SyntaxError,
            },
            4 => match aa_tag {
                // Command: UnsetEnvVar #(NonAssoc, 0)
                AAEnd => Action::Reduce(3),
                _ => Action::SyntaxError,
            },
            5 => match aa_tag {
                ASSIGN => Action::Shift(8),
                _ => Action::SyntaxError,
            },
            6 => match aa_tag {
                WS => Action::Shift(9),
                _ => Action::SyntaxError,
            },
            7 => match aa_tag {
                ID => Action::Shift(10),
                _ => Action::SyntaxError,
            },
            8 => match aa_tag {
                ID => Action::Shift(12),
                STRING => Action::Shift(11),
                _ => Action::SyntaxError,
            },
            9 => match aa_tag {
                ID => Action::Shift(13),
                _ => Action::SyntaxError,
            },
            10 => match aa_tag {
                // Command: STRING WS ID #(NonAssoc, 0)
                AAEnd => Action::Reduce(1),
                _ => Action::SyntaxError,
            },
            11 => match aa_tag {
                // SetEnvVar: ID "=" STRING #(NonAssoc, 0)
                AAEnd => Action::Reduce(4),
                _ => Action::SyntaxError,
            },
            12 => match aa_tag {
                // SetEnvVar: ID "=" ID #(NonAssoc, 0)
                AAEnd => Action::Reduce(5),
                _ => Action::SyntaxError,
            },
            13 => match aa_tag {
                // UnsetEnvVar: "unset" WS ID #(NonAssoc, 0)
                AAEnd => Action::Reduce(6),
                _ => Action::SyntaxError,
            },
            _ => panic!("illegal state: {aa_state}"),
        };
    }

    fn production_data(production_id: u32) -> (AANonTerminal, usize) {
        match production_id {
            0 => (AANonTerminal::AAStart, 1),
            1 => (AANonTerminal::Command, 3),
            2 => (AANonTerminal::Command, 1),
            3 => (AANonTerminal::Command, 1),
            4 => (AANonTerminal::SetEnvVar, 3),
            5 => (AANonTerminal::SetEnvVar, 3),
            6 => (AANonTerminal::UnsetEnvVar, 3),
            _ => panic!("malformed production data table"),
        }
    }

    fn goto_state(lhs: &AANonTerminal, current_state: u32) -> u32 {
        return match current_state {
            0 => match lhs {
                AANonTerminal::Command => 1,
                AANonTerminal::SetEnvVar => 3,
                AANonTerminal::UnsetEnvVar => 4,
                _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
            },
            _ => panic!("Malformed goto table: ({lhs}, {current_state})"),
        };
    }

    fn do_semantic_action<F: FnMut(String, String)>(
        &mut self,
        aa_production_id: u32,
        aa_rhs: Vec<AttributeData>,
        mut aa_inject: F,
    ) -> AttributeData {
        let mut aa_lhs = if let Some(a) = aa_rhs.first() {
            a.clone()
        } else {
            AttributeData::default()
        };
        match aa_production_id {
            1 => {
                // Command: STRING WS ID #(NonAssoc, 0)
                println!("{:?} {:?}", aa_rhs[0].string(), aa_rhs[2].id());
            }
            2 => {
                // Command: SetEnvVar #(NonAssoc, 0)

                let (var, value) = aa_rhs[0].set_env_var();
                *self = Command::SetEnvVar(var.to_string(), value.to_string());
            }
            4 => {
                // SetEnvVar: ID "=" STRING #(NonAssoc, 0)

                println!("ASSIGNMENT");
                aa_lhs = AttributeData::SetEnvVar(
                    aa_rhs[0].id().to_string(),
                    aa_rhs[2].string().to_string(),
                );
            }
            5 => {
                // SetEnvVar: ID "=" ID #(NonAssoc, 0)
                println!("ASSIGNMENT");
                aa_lhs = AttributeData::SetEnvVar(
                    aa_rhs[0].id().to_string(),
                    aa_rhs[2].id().to_string(),
                );
            }
            _ => aa_inject(String::new(), String::new()),
        };
        aa_lhs
    }
}
